Update Generators
LaunchPadLab/token-master pull request #13
Opened 2017-03-30 16:35 UTC by inveterateliterate

Updated migration generator: 
- properly creates migration file
- file name is dynamic to allow subsequent migrations

Updated install generator:
- accepts tokenable arguments

Using dummy app

2017-04-05 14:35 UTC, davemcorwin requested changes
Cool.

1. Make sure to add `.DS_Store` files to your .gitignore. To do this effectively, delete them, commit the changes, then add to .gitignore.

2. Does the migration generator create the initializer if it doesn't already exist? Is the install generator something that users will still use?

2017-04-10 19:45 UTC, davemcorwin commented
@inveterateliterate any updates?

2017-04-12 20:59 UTC, inveterateliterate commented
@davemcorwin updated

2017-04-13 18:27 UTC, davemcorwin approved these changes

2017-04-14 03:20 UTC, merged