Update simplecov and test_helper
LaunchPadLab/token-master pull request #36
Opened 2017-04-21 22:38 UTC by inveterateliterate

2017-04-24 21:05 UTC, davemcorwin requested changes

2017-04-24 21:05 UTC, davemcorwin commented on Gemfile
> +  gem 'simplecov', :require => false, :group => :test
its already in the test group :)

soooo, we shouldn't need this here and in the gemspec...

2017-04-24 22:26 UTC, inveterateliterate commented
@dave I updated those files

2017-04-25 00:59 UTC, davemcorwin approved these changes

2017-04-25 13:45 UTC, merged